### ISSUE TITLE
CODEOWNERS 추가 요청 및 WebHook 활성화

### ISSUE THREAD

**Issue by dodeca05** [HunnitBeasts/KelogBackend#12]
# 🚀 Issue 템플릿

## 📝 설명

pull request 시 Reviewers에 사람을 추가하지 않으면 pull request 알람이 오지 않습니다.
pull request 알람을 위하여 전용 discord channel을 파고 이에 pull request 알람을 보내는 webhook 설정도 요청드립니다.
### 🔍 재현 방법

1. '...'로 이동
2. '...'을 클릭
3. '...'까지 스크롤
4. 오류 발생

### 🤔 기대 동작

pull request 등록시 이에 대한 알람
### 😱 실제 동작

누군가 알려주기 전까지 pull request 등록 여부를 알 수 없음
### 🖥 환경

- **운영 체제:** [예: Windows, MacOS]
- **브라우저:** [예: Chrome, Safari]
- **버전:** [예: 22]

## 💡 기능 요청
CODEOWNERS 파일 작성 요청 

discord channel 개설 및 WebHook 등록 요청

**Comment by yu-teacher** [comment]
네 해드리겠읍니다. 혹시 개발자들
![image](https://github.com/HunnitBeasts/KelogBackend/assets/119153725/0ab665b3-c819-4939-8a02-ce26bcf8184b)
이용하는 것이 불편하지 않다면 거따가 하겠읍니다.

**Comment by yu-teacher** [comment]
해결 했습니다.
