### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by dodeca05** [HunnitBeasts/KelogBackend#39]
# 1. 비효율적인 ExceptionHandler

다음은 리뷰를 위해 캐치해낸 코드입니다.

<pre>
<code>
@Converter(autoApply = true)
public class PostTypeConverter implements AttributeConverter<PostType,Integer> {

    @Override //entity-> db 값 추가할때 integer로 변환
    public Integer convertToDatabaseColumn(PostType postType) {
        if(postType == null)
            throw new IllegalArgumentException(ErrorCode.NO_POST_TYPE_ERROR.getMessage()); // TODO : 나중에 service 분리 하자잇
        return postType.getTypeNum();
    }
</code>
</pre>

<pre>
<code>
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponseDTO> handleIllegalArgumentException(IllegalArgumentException e) {
        ErrorResponseDTO dto = createErrorResponseFromMessage(e.getMessage());
        logErrorResponse(dto);
        return ResponseEntity.status(dto.getStatusCode()).body(dto);
    }
    private ErrorResponseDTO createErrorResponseFromMessage(String errorMessage) {
        if (!isErrorCode(errorMessage))
            return new ErrorResponseDTO(ErrorCode.OCCUR_UNKNOWN_TYPE_ERROR, errorMessage);
        else {
            if (errorMessage.length() == 10)
                return new ErrorResponseDTO(findErrorCode(errorMessage));
            String code = errorMessage.substring(0, 10);
            String message = errorMessage.substring(10);
            ErrorCode errorCode = findErrorCode(code);
            return new ErrorResponseDTO(errorCode, message);
        }
    }
    private ErrorCode findErrorCode(String code) {
        return errorCodes.stream()
                .filter(errorCode -> errorCode.getCode().equals(code.trim()))
                .findFirst()
                .orElse(ErrorCode.OCCUR_UNKNOWN_TYPE_ERROR);
    }
</code>
</pre>

위의 Exception 처리 과정을 설명하면 Exception용 처리용으로 생성해둔 enum에서 **사용자용 메세지를** Exception에 담아서 Handler에서 처리하도록 하였고 Stream을 통한 검색으로 dto를 생성하도록 하였습니다.

서비스 코드) -Exception 발생-> 사용자용 String 메세지 전달 -> Exception Handler 에서 해당 메세지를 검색 -> 처리

위와같은 구조는 효율적이지 않습니다. 특히 String을 이용한 논리작업 및 검색은 생각보다 많은 성능이 필요합니다. 
특히 사용자용 메세지를 이용한 논리작업은 다소 이상하게 보입니다.

더욱더 간단하고 간결한 구조로 리팩토링 했으면 좋겠습니다.
서비스 코드)-Exception 발생-> error eunm전달 ->Exception Handler 처리

아래는 예제 코드 입니다.
<pre>
<code>
@Getter
@RequiredArgsConstructor
public class ExpectException extends Exception{
    private final ErrorCode errorCode;
}
</code>
</pre>

<pre>
<code>
   @SneakyThrows
    @Override
    public Integer convertToDatabaseColumn(PostType postType) {
        if(postType == null)
            throw new ExpectException(ErrorCode.NO_POST_TYPE_ERROR);
        return postType.getTypeNum();
    }
</code>
</pre>
<pre>
<code>
    @ExceptionHandler(ExpectException.class)
    public ResponseEntity<ErrorResponseDTO> expectHandleException(ExpectException e) {
        ErrorCode errorCode=e.getErrorCode();
        logError(errorCode);
        ErrorResponseDTO dto = new ErrorResponseDTO(errorCode);
        return ResponseEntity.status(dto.getStatusCode()).body(dto);
    }
</code>
</pre>
위와 같은 구조로 좀 더 빠르고 간단하게 에러 로깅 및 처리가 가능합니다.

PS 사용자에게 돌려줄 DTO를 기반으로 logging 하는 형태도 좀 이상합니다.
 내부 기록용 메세지 및 코드와 사용자에게 보여줄 내용이 정확히 구별되는 것이 좋습니다.

cc https://github.com/HunnitBeasts/KelogBackend/pull/35

# 2. enum의 안좋은 사용 형태
![image](https://github.com/HunnitBeasts/KelogBackend/assets/49556303/6d56a351-fcfc-478a-92dd-7c0d7189cca1)

해당 시스템 개발자나 관리자가 아닌 사용자에게 보낼 메세지를 enum으로 저장하는 것은 그닥 좋은 형태가 아닙니다.
위와 같은 메세지는 별도의 언어팩 파일로 관리하는걸 추천합니다.

예를 들어 해당 서비스를 글로벌로 출시하기로 결정하였고 이제 영어와 프랑스어등 다른 언어를 넣기로 결정했다면 소스코드를 수정해야 되는 서비스 VS 언어팩 yml 또는 xml 기타등등... 만 수정해도 되는 서비스 어느 형태가 더 좋아 보이나요?

또한 code 와 status가 어느정도의 상관 관계를 보이고 있습니다. 이 부분은 일일이 상수로 저장하는 것 보다 일부 예외를 제외하고 논리적으로 처리하는 형태가 enum을 경량화 시킬 수 있을 겁니다.
예) CODE B 로 시작할 경우 무조건 status 404

# 3. 코드의 스파게티화

해당 소스코드는 점점더 스파게티화 되고 있습니다. 이럴 경우 처음부터 프로젝트를 진행한 사람이 아니면 이 이후 유지보수가 불가능해 질 수 있습니다. 따라서 이럴 경우에는 각 controller, service 등 패캐지를 도메인 단위로 분리하여 넣는 것을 추천합니다.

예제

root
    ├── post
    │    ├── config
    │    ├── controller
    │    ├── service
    │    ├── repository
    │    ├── model
    │    ├── dto
    │    └── exception
   ├── user
    │    ├── config
    │    ├── controller
    │    ├── service
    │    ├── repository
    │    ├── model
    │    ├── dto
    │    └── exception
   ├── comment
    │    ├── config
    │    ├── controller
    │    ├── service
    │    ├── repository
    │    ├── model
    │    ├── dto
    │    └── exception
    └── common // 공통 소스
         ├── config
         ├── controller
         ├── service
         ├── repository
         ├── model
         ├── dto
         └── exception

**Comment by yu-teacher** [comment]
1,2 우솔님이 하는중 3 승민님이 할 예정

**Comment by dnthf652** [comment]
의견을 반영하여 exception handler, enum을 수정하였습니다

**Comment by yu-teacher** [comment]
3번 완료 풀리퀘스트 올림 확인요망

1번 배열 user, post, comment, image, common 등 5개의 방법으로 구분 하였습니다.
2번 배열 auth, user, post, postassist, comment, image, common등 7개의 방법으로 구분 하였습니다.
